# Site
repository: jeffchy/jeffchy.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Chengyue Jiang
title: PhD student at ShanghaiTech
email: jiangchy@shanghaitech.edu.cn
website: https://jeffchy.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  jeffchy
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ChengyueJiang
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: https://jeffchy.github.io/
#  icon: fas fa-globe
#   url: https://jeffchy.github.io/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/me.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Chengyue Jiang and I'm currently a 4th year PhD student at ShanghaiTech University. 
  I majored in Computer Science, and I'm doing research focusing on Natural Language Processing <mark>(NLP)</mark>, and I'm supervised by Prof. [Kewei Tu](http://sist.shanghaitech.edu.cn/faculty/).
  
  More specifically, My NLP research interests are 
  - use <mark>symbolic knowledge</mark> (e.g. Regular Expressions) to help NLP models reach better performance and have better interpretability on NLP tasks. 
  - <mark>information extraction</mark>, such as entity typing and named entity recognition.
  - investigate the <mark>ontological knowledge</mark> in large pretrained language models. 
  
  <font size=5> I'm currently <mark>VERY INTERESTED</mark> at <mark>Large Language Models (LLM)</mark> and keeps exploring and trying related techniques<font>
  
  <font size=5> I'm <mark>open to the job market this Autumn</mark>, feel free to contact me through my email: jiangchy@shanghaitech.edu.cn <font>
  
content:
  - title: Education # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
     - I recieve my <mark>Bachelor</mark> degree in Computer Science in ShanghaiTech University, (June 2015 - June 2019).
     - And I'm now a <mark>PhD</mark> student in ShanghaiTech University, supervised by Prof. [Kewei Tu](http://sist.shanghaitech.edu.cn/faculty/).
      
  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: EACL 2023
        description: |
          **Chengyue Jiang**, Yong Jiang, Weiqi Wu, Yuting Zheng, Pengjun Xie, Kewei Tu **"COMBO: A Complete Benchmark for Open KG Canonicalization"**. 
          In *Proceedings of the 17th Conference of the European Chapter of the Association for Computational Linguistics: Main Volume*. [(Paper)](https://github.com/jeffchy/COMBO) [(Code)](https://github.com/jeffchy/COMBO)
      - layout: left
        title: EMNLP 2022
        description: |
          **Chengyue Jiang**, Yong Jiang, Weiqi Wu, Zhongqiang Huang, Pengjun Xie, Kewei Tu **"Modeling Label Correlations for Ultra-Fine Entity Typing with Neural Pairwise Conditional Random Field"**. 
          In *Proceedings of the 2022 Conference on Empirical Methods in Natural Language Processing*. [(Paper)](https://aclanthology.org/2022.emnlp-main.747/) [(Code)](https://github.com/jeffchy/NPCRF)
      - layout: left
        title: EMNLP 2021
        description: |
          **Chengyue Jiang**, Zijian Jin, Kewei Tu. **"Neuralizing Regular Expressions for Slot Filling"**. 
          In *Proceedings of the 2021 Conference on Empirical Methods in Natural Language Processing*. [(Paper)](https://aclanthology.org/2021.emnlp-main.747/) [(Code)](https://github.com/jeffchy/RE2NN-SEQ)
      - layout: left
        title: EMNLP 2020
        description: |
          **Chengyue Jiang**, Yinggong Zhao, Shanbo Chu, Libin Shen, and Kewei Tu. **"Cold-start and Interpretability: Turning Regular Expressions into Trainable Recurrent Neural Networks"**. 
          In *Proceedings of the 2020 Conference on Empirical Methods in Natural Language Processing*. [(Paper)](https://www.aclweb.org/anthology/2020.emnlp-main.258/) [(Code)](https://github.com/jeffchy/RE2RNN)
      - layout: left
        title: Findings of EMNLP 2020
        description: |
          **Chengyue Jiang**, Zhonglin Nian, Kaihao Guo, Shanbo Chu, Yinggong Zhao, Libin Shen, and Kewei Tu. **"Learning Neumeral Embeddings"**. 
          *In Findings of the Association for Computational Linguistics: EMNLP 2020*.  [(Paper)](https://www.aclweb.org/anthology/2020.findings-emnlp.235/) [(Code)](https://github.com/jeffchy/Learning-Numeral-Embeddings)
      - layout: left
        title: CoNLL 2019
        description: |
          Xinyu Wang, Yixian Liu, Zixia Jia, **Chengyue Jiang**, and Kewei Tu. "**ShanghaiTech at MRP 2019: Sequence-to-Graph Transduction with Second-Order Edge Inference for Cross-Framework Meaning Representation Parsing**". 
          *In Proceedings of the 23rd Conference on Computational Natural Language Learning (CoNLL 2019)*. [(Paper)](http://faculty.sist.shanghaitech.edu.cn/faculty/tukw/conll19.pdf) 
          [(Poster)](http://faculty.sist.shanghaitech.edu.cn/faculty/tukw/conll19-poster.pdf)
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NLP Research Intern
        sub_title: Alibaba Damo Academy, Hangzhou
        caption: August 2021 -- Present
        description: |
          Doing some research about <mark>pretraining language model</mark> and <mark>information extraction</mark>. Act as the core developer of the entity typing part of the [Adaseq](https://github.com/modelscope/AdaSeq/blob/master/) Project in DAMO academy. 
      - layout: left
        title: Software Intern
        sub_title: Honeywell, Nanjing
        caption: July 2018 -- September 2018
        description: |
          Doing some early research on using image captioning to help fault detection. Using simple sequence to sequence architecture, and implemented using Keras. 
      - layout: left
        title: Web Intern
        sub_title: Boonray Technology, Shanghai
        caption: July 2016 -- September 2016
        description: |
          Software engineer internship. Participating in developing a webapp using Django backend and MySQL. The webapp is a simple
          cloud platform, used for managing costumers.
          
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Adaseq 
        sub_title: one of core contributors
        description: |
           [Adaseq](https://github.com/modelscope/AdaSeq/blob/master/) is the open source sequence understanding libarary presented by DAMO NLP. It contains SOTA Named Entity Recognition, 
           Entity Typing, Relation Extraction models. I act as the core developer of the entity typing part of the [Adaseq](https://github.com/modelscope/AdaSeq/blob/master/) Project in DAMO academy.  
           Implemente and replicate entity typing models including multi-label MLC, [NPCRF](https://aclanthology.org/2022.emnlp-main.747/), [MCCE](https://arxiv.org/abs/2212.09125), Prompt Learning, etc.
      - layout: left
        title: RegExp to Neural Network
        sub_title: author
        description: |
          The source codes([RE2NN](https://github.com/jeffchy/RE2RNN),[RE2NN-SEQ](https://github.com/jeffchy/RE2RNN-SEQ)) of my papers  **"Cold-start and Interpretability: Turning Regular Expressions into Trainable Recurrent Neural Networks"** and  **"Neuralizing Regular Expressions for Slot Filling"**, reaches over 130 stars on GitHub.
          The repos change regular expressions for text classification and slot filling into neural networks.
          
  - title: Services # Title for the section
    layout: text # Type of content section (list/text)
    content: | # this will include new lines to allow paragraphs
     - ACL2023 EACL2023 AACL2022 ICLR2022
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
